apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  project: default
  source:
    repoURL: 'https://github.com/shreyasgune/dotnet-game-api.git'
    targetRevision: 'see_sharp_game_api'
    path: 'game-web-api-dotnet/helm-chart/kube-prometheus-stack'  # Set the path to the directory containing your manifests
    helm:
      valueFiles:
        - values.yaml  # Add any specific values files if needed
        - values/custom-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true