{
 "title": "dotnet-game-api-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "SYSTEM STATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"dotnet-game-api-dotnet-game-api\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SYSTEM STATE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"dotnet-game-api-dotnet-game-api\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration 95th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests in 1H",
   "type": "timeseries",
   "description": "This query counts the number of requests that were completed in less than or equal to 0.01 seconds over the last hour.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count_over_time(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{le=\"0.01\"}[1h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Time used by Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "avg(http_request_duration_seconds_sum{}) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAW LOG",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{namespace=\"dotnet-game-api\"}"
    }
   ]
  },
  {
   "title": "Queries Made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "player_requests_total{namespace=\"dotnet-game-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Player quries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(player_requests_total{namespace=\"dotnet-game-api\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}