name: Build Docker Image

on:
  pull_request:
    paths:
      - 'game-web-api-dotnet/Dockerfile' 
      - 'game-web-api-dotnet/GameBackend/Program.cs'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: "${GITHUB_SHA:0:7}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd game-web-api-dotnet
          IMAGE_TAG="${GITHUB_SHA:0:7}"
          docker build -t shreyasgune/dotnet-web-api:$IMAGE_TAG .

      - name: Start Docker container in detached mode
        run: |
          IMAGE_TAG="${GITHUB_SHA:0:7}"
          docker run -d --name test-$IMAGE_TAG -p 8080:8080 shreyasgune/dotnet-web-api:$IMAGE_TAG
      
      - name: Wait for container start, about 5 sec
        run: sleep 5

      - name: Test out the running container
        run: |
          docker exec test-$IMAGE_TAG curl http://localhost:8080/metrics

      - name: Test Port mapping as well
        run: |
          curl http://localhost:8080/metrics

      - name: Check logs
        run: |
          docker logs test-$IMAGE_TAG