name: Build Docker Image

on:
  pull_request:
    paths:
      - 'Dockerfile' 
      - 'game-web-api-dotnet/GameBackend'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (if needed)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          cd game-web-api-dotnet
          IMAGE_TAG="${GITHUB_SHA:0:7}"
          docker build -t shreyasgune/dotnet-web-api:$IMAGE_TAG .
